#pragma once

#include <cstdint>

namespace SkyrimTogetherVR::GameplayAdapter::LocalGameplayCapture
{
// These entry points are owned by the bridge's game-thread integration.  They
// never expose game pointers or variable-size game data through the bridge.
void Initialize() noexcept;
// Local gameplay capture remains dormant until the mapped client explicitly
// arms it for the current session.
void Arm() noexcept;
void CapturePeriodic() noexcept;
// These tokens suppress the exact CommonLib quest event generated by an
// inbound mutation. They are short-lived and must be cancelled if that
// mutation is rejected synchronously.
using QuestSuppressionToken = std::uint64_t;
[[nodiscard]] QuestSuppressionToken ArmQuestStartStopSuppression(
    std::uint32_t a_questLocalFormId,
    bool a_started) noexcept;
[[nodiscard]] QuestSuppressionToken ArmQuestStageSuppression(
    std::uint32_t a_questLocalFormId,
    std::uint16_t a_stage) noexcept;
void CancelQuestSuppression(QuestSuppressionToken a_token) noexcept;
using LockSuppressionToken = std::uint64_t;
[[nodiscard]] LockSuppressionToken ArmLockSuppression(
    std::uint32_t a_referenceLocalFormId, bool a_locked, std::uint8_t a_lockLevel) noexcept;
void CancelLockSuppression(LockSuppressionToken a_token) noexcept;
// Inbound party XP is applied through the same engine API observed by the
// polling path. Suppress the next change for that skill so it is not echoed
// back to the server; the suppression expires if the engine rejects it.
[[nodiscard]] bool ArmExperienceSuppression(std::uint32_t a_actorValue) noexcept;
// Observation is keyed only by stable local reference form IDs.  The capture
// module resolves each ID afresh on the game thread; no native pointer crosses
// the mapped ABI or survives a lifecycle reset.
bool StartNpcObservation(std::uint32_t a_localReferenceFormId) noexcept;
void StopNpcObservation(std::uint32_t a_localReferenceFormId) noexcept;
// Called by the exact VR Actor::SpeakSound hook after the engine accepts a
// locally simulated NPC voice line. The mapped client resolves ownership and
// the canonical server actor ID; no game pointer crosses this boundary.
bool CaptureDialogueVoice(std::uint32_t a_localActorFormId, const char* a_resourcePath) noexcept;
void Reset() noexcept;
} // namespace SkyrimTogetherVR::GameplayAdapter::LocalGameplayCapture
