# Building the server:
#   x64:   $ docker build -t imagename .
#   arm64: $ docker build --platform linux/arm64 -t imagename .
#   multi-platform (build and push):
#     $ docker buildx create --name st-server-multiarch --use
#     $ docker buildx build --platform linux/amd64,linux/arm64 -t imagename:tag --push .

FROM debian:12 AS builder

ENV DEBIAN_FRONTEND=noninteractive
ENV XMAKE_ROOT=y
SHELL ["/bin/bash", "-c"]

# Passed from the workflow; needed so that xmake always picks github.com as host
ARG GITHUB_ACTIONS

# Get packages and xmake

RUN apt-get update && apt-get install -y --no-install-recommends build-essential curl pkg-config git ca-certificates unzip libssl-dev && \
    rm -rf /var/lib/apt/lists/* && \
    curl -fsSL https://xmake.io/shget.text | bash

WORKDIR /src

# Copy the complete xmake include graph explicitly. These are the only source
# inputs needed to resolve dependencies; keep the full source copy below the
# dependency layer so ordinary source edits do not invalidate it.
COPY xmake.lua /src/xmake.lua
COPY Code/xmake.lua /src/Code/xmake.lua
COPY Code/admin/xmake.lua /src/Code/admin/xmake.lua
COPY Code/admin_protocol/xmake.lua /src/Code/admin_protocol/xmake.lua
COPY Code/base/xmake.lua /src/Code/base/xmake.lua
COPY Code/client/xmake.lua /src/Code/client/xmake.lua
COPY Code/common/xmake.lua /src/Code/common/xmake.lua
COPY Code/components/xmake.lua /src/Code/components/xmake.lua
COPY Code/components/console/xmake.lua /src/Code/components/console/xmake.lua
COPY Code/components/es_loader/xmake.lua /src/Code/components/es_loader/xmake.lua
COPY Code/components/imgui/xmake.lua /src/Code/components/imgui/xmake.lua
COPY Code/components/resources/xmake.lua /src/Code/components/resources/xmake.lua
COPY Code/encoding/xmake.lua /src/Code/encoding/xmake.lua
COPY Code/higgs_bridge/xmake.lua /src/Code/higgs_bridge/xmake.lua
COPY Code/immersive_elf/xmake.lua /src/Code/immersive_elf/xmake.lua
COPY Code/immersive_launcher/xmake.lua /src/Code/immersive_launcher/xmake.lua
COPY Code/planck_bridge/xmake.lua /src/Code/planck_bridge/xmake.lua
COPY Code/server/xmake.lua /src/Code/server/xmake.lua
COPY Code/server_runner/xmake.lua /src/Code/server_runner/xmake.lua
COPY Code/tests/xmake.lua /src/Code/tests/xmake.lua
COPY Code/tp_process/xmake.lua /src/Code/tp_process/xmake.lua
COPY Code/vr_gameplay_bridge/xmake.lua /src/Code/vr_gameplay_bridge/xmake.lua
COPY Code/vr_tick_bridge/xmake.lua /src/Code/vr_tick_bridge/xmake.lua
COPY Code/vrik_bridge/xmake.lua /src/Code/vrik_bridge/xmake.lua
COPY Libraries/xmake.lua /src/Libraries/xmake.lua
COPY Libraries/CommonLibSSE-NG/xmake.lua /src/Libraries/CommonLibSSE-NG/xmake.lua
COPY Libraries/TiltedConnect/xmake.lua /src/Libraries/TiltedConnect/xmake.lua
COPY Libraries/TiltedHooks/xmake.lua /src/Libraries/TiltedHooks/xmake.lua
COPY Libraries/TiltedReverse/xmake.lua /src/Libraries/TiltedReverse/xmake.lua
COPY Libraries/TiltedUI/xmake.lua /src/Libraries/TiltedUI/xmake.lua

# Resolve package dependencies before declaring revision-specific provenance.
# This layer, including its BuildKit caches, can therefore be reused when only
# the build identity changes.
RUN --mount=type=cache,target=/root/.xmake/packages \
    --mount=type=cache,target=/root/.xmake/repositories \
    source ~/.xmake/profile && \
    xmake config -y -m release && \
    xmake require -y

# Copy source only after dependency resolution so source revisions retain the
# legacy-builder dependency layer cache.
COPY . /src

# Keep revision-specific args below the expensive toolchain and package layers.
# They are validated immediately before being written into the build artifact.
ARG STVR_BUILD_BRANCH
ARG STVR_BUILD_COMMIT

RUN [[ -n "$STVR_BUILD_BRANCH" && "$STVR_BUILD_BRANCH" != "none" && "$STVR_BUILD_BRANCH" != unknown-* && "$STVR_BUILD_BRANCH" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] || \
        { echo "Invalid STVR_BUILD_BRANCH provenance." >&2; exit 2; } && \
    [[ -n "$STVR_BUILD_COMMIT" && "$STVR_BUILD_COMMIT" != "none" && "$STVR_BUILD_COMMIT" != unknown-* && "$STVR_BUILD_COMMIT" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] || \
        { echo "Invalid STVR_BUILD_COMMIT provenance." >&2; exit 2; }

RUN --mount=type=cache,target=/root/.xmake/packages \
    --mount=type=cache,target=/root/.xmake/repositories \
    source ~/.xmake/profile && \
    mkdir -p build && \
    printf '#pragma once\n// This file was autogenerated by the Docker build.\n#define BUILD_BRANCH "%s"\n#define BUILD_COMMIT "%s"\n' "$STVR_BUILD_BRANCH" "$STVR_BUILD_COMMIT" > Code/common/BuildInfo.h.in && \
    xmake -y SkyrimServerRunner && \
    grep -Fqx "#define BUILD_BRANCH \"$STVR_BUILD_BRANCH\"" build/BuildInfo.h && \
    grep -Fqx "#define BUILD_COMMIT \"$STVR_BUILD_COMMIT\"" build/BuildInfo.h && \
    xmake install -y -o package SkyrimTogetherServer && \
    xmake install -y -o package SkyrimServerRunner

# Actual server runtime image; (todo: maybe reconsider 'distroless' in the future)

FROM debian:12-slim AS runtime

WORKDIR /st-server

COPY --from=builder \
    /src/package/lib/libSTServer.so \
    /src/package/bin/SkyrimTogetherServer \
    /st-server/

ENTRYPOINT ["./SkyrimTogetherServer"]
EXPOSE 10578/udp
