# Building the server:
#   x64:   $ docker build -t imagename .
#   arm64: $ docker build --platform linux/arm64 -t imagename .
#   multi-platform (build and push):
#     $ docker buildx create --name st-server-multiarch --use
#     $ docker buildx build --platform linux/amd64,linux/arm64 -t imagename:tag --push .

FROM debian:12 AS builder

ENV DEBIAN_FRONTEND=noninteractive
ENV XMAKE_ROOT=y
SHELL ["/bin/bash", "-c"]

# Passed from the workflow; needed so that xmake always picks github.com as host
ARG GITHUB_ACTIONS
ARG STVR_BUILD_BRANCH
ARG STVR_BUILD_COMMIT

RUN [[ -n "$STVR_BUILD_BRANCH" && "$STVR_BUILD_BRANCH" != "none" && "$STVR_BUILD_BRANCH" != unknown-* && "$STVR_BUILD_BRANCH" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] || \
        { echo "Invalid STVR_BUILD_BRANCH provenance." >&2; exit 2; } && \
    [[ -n "$STVR_BUILD_COMMIT" && "$STVR_BUILD_COMMIT" != "none" && "$STVR_BUILD_COMMIT" != unknown-* && "$STVR_BUILD_COMMIT" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*$ ]] || \
        { echo "Invalid STVR_BUILD_COMMIT provenance." >&2; exit 2; }

# Get packages and xmake

RUN apt-get update && apt-get install -y --no-install-recommends build-essential curl pkg-config git ca-certificates unzip libssl-dev && \
    rm -rf /var/lib/apt/lists/* && \
    curl -fsSL https://xmake.io/shget.text | bash

# Copy source and build

WORKDIR /src
COPY . /src

RUN --mount=type=cache,target=/root/.xmake/packages \
    --mount=type=cache,target=/root/.xmake/repositories \
    source ~/.xmake/profile && \
    xmake config -y -m release && \
    mkdir -p build && \
    printf '#pragma once\n// This file was autogenerated by the Docker build.\n#define BUILD_BRANCH "%s"\n#define BUILD_COMMIT "%s"\n' "$STVR_BUILD_BRANCH" "$STVR_BUILD_COMMIT" > build/BuildInfo.h && \
    grep -Fqx "#define BUILD_BRANCH \"$STVR_BUILD_BRANCH\"" build/BuildInfo.h && \
    grep -Fqx "#define BUILD_COMMIT \"$STVR_BUILD_COMMIT\"" build/BuildInfo.h && \
    xmake -y SkyrimServerRunner && \
    xmake install -y -o package SkyrimTogetherServer && \
    xmake install -y -o package SkyrimServerRunner

# Actual server runtime image; (todo: maybe reconsider 'distroless' in the future)

FROM debian:12-slim AS runtime

WORKDIR /st-server

COPY --from=builder \
    /src/package/lib/libSTServer.so \
    /src/package/bin/SkyrimTogetherServer \
    /st-server/

ENTRYPOINT ["./SkyrimTogetherServer"]
EXPOSE 10578/udp
