#!/usr/bin/env python3
"""Generate the VR graph catalog from the original descriptor constructors."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "Code/encoding/Structs/Skyrim"
DESCRIPTOR_OUTPUT = ROOT / "Code/vr_gameplay_bridge/AnimationGraphDescriptors.generated.inc"
SHAPE_OUTPUT = ROOT / "Code/vr_common/VRAnimationGraphShapes.generated.inc"

def variables(body):
    enum = re.search(r"enum Variables\s*\{(.*?)\};", body, re.S)
    if not enum:
        raise ValueError("missing Variables enum")
    names = set(re.findall(r"\b(k\w+)\s*=\s*\d+\s*,", enum.group(1)))
    start = body.find("AnimationGraphDescriptor(")
    if start < 0:
        raise ValueError("missing descriptor lists")
    groups = []
    cursor = start
    while len(groups) != 3:
        cursor = body.find("{", cursor)
        if cursor < 0:
            raise ValueError("missing descriptor lists")
        end = body.find("}", cursor)
        if end < 0:
            raise ValueError("unterminated descriptor list")
        groups.append(body[cursor + 1:end])
        cursor = end + 1
    lists = []
    for group in groups:
        identifiers = re.findall(r"\b(k\w+)\b", group)
        if not identifiers or any(item not in names for item in identifiers):
            raise ValueError("missing enum name")
        lists.append([item[1:] for item in identifiers])
    return lists

def main():
    entries = []
    shapes = {}
    for path in sorted(SOURCE.glob("AnimationGraphDescriptor_*.cpp")):
        body = path.read_text()
        header = SOURCE / (path.stem + ".h")
        key = re.search(r"m_key\s*=\s*(\d+)", header.read_text()) or re.search(r"\bkey\s*=\s*(\d+)", body)
        if not key:
            raise ValueError(f"{path}: missing key")
        lists = variables(body)
        if len(lists[0]) > 64 or len(lists[1]) + len(lists[2]) > 63:
            raise ValueError(f"{path}: protocol limit exceeded")
        direction_indices = [index for index, value in enumerate(lists[1]) if value == "Direction"]
        if len(direction_indices) != 1:
            raise ValueError(f"{path}: expected exactly one Direction float")
        shape = (len(lists[0]), len(lists[1]), len(lists[2]))
        direction_index = direction_indices[0]
        existing_direction = shapes.get(shape)
        if existing_direction is not None and existing_direction != direction_index:
            raise ValueError(
                f"{path}: duplicate descriptor shape {shape} disagrees on Direction index "
                f"({existing_direction} != {direction_index})"
            )
        shapes[shape] = direction_index
        entries.append((path.stem.removeprefix("AnimationGraphDescriptor_"), int(key.group(1)), lists))
    if len(entries) != 32 or len({entry[1] for entry in entries}) != len(entries):
        raise ValueError("expected 32 unique descriptor keys")
    lines = ["// Generated by Tools/SkyrimVR/generate_animation_graph_descriptors.py; do not edit.", ""]
    for name, key, lists in entries:
        safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
        for suffix, values in zip(("Boolean", "Float", "Integer"), lists):
            quoted = ", ".join(f'\"{value}\"' for value in values)
            lines.append(f"constexpr std::string_view k{safe}{suffix}Names[]{{{quoted}}};")
    lines.append("")
    lines.append("constexpr AnimationGraphDescriptor kDescriptors[]{")
    for name, key, _ in entries:
        safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
        lines.append("    {" + str(key) + "ull, k" + safe + "BooleanNames, k" + safe + "FloatNames, k" + safe + "IntegerNames},")
    lines.append("};")
    descriptor_output = "\n".join(lines) + "\n"

    shape_lines = ["// Generated by Tools/SkyrimVR/generate_animation_graph_descriptors.py; do not edit.", "",
                   "inline constexpr DescriptorShape kKnownDescriptorShapes[]{"]
    for boolean_count, float_count, integer_count in sorted(shapes):
        shape_lines.append(
            f"    {{{boolean_count}, {float_count}, {integer_count}, {shapes[(boolean_count, float_count, integer_count)]}}},"
        )
    shape_lines.extend([
        "};",
        "inline constexpr std::size_t kKnownDescriptorShapeCount = sizeof(kKnownDescriptorShapes) / sizeof(kKnownDescriptorShapes[0]);",
        "",
    ])
    shape_output = "\n".join(shape_lines)
    if "--check" in sys.argv:
        if not DESCRIPTOR_OUTPUT.exists() or DESCRIPTOR_OUTPUT.read_text() != descriptor_output:
            raise SystemExit("generated descriptor catalog is stale")
        if not SHAPE_OUTPUT.exists() or SHAPE_OUTPUT.read_text() != shape_output:
            raise SystemExit("generated graph-shape catalog is stale")
    else:
        DESCRIPTOR_OUTPUT.write_text(descriptor_output)
        SHAPE_OUTPUT.write_text(shape_output)

if __name__ == "__main__":
    main()
