#!/usr/bin/env python3
"""Static cache-boundary contract for the dedicated server Docker build."""

from __future__ import annotations

import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[3]
DOCKERFILE = ROOT / "Dockerfile"
BUILD_SCRIPT = ROOT / "Tools" / "SkyrimVR" / "server" / "build_server_image.sh"
DEPENDENCY_MANIFESTS = (
    "xmake.lua",
    "Code/xmake.lua",
    "Code/admin/xmake.lua",
    "Code/admin_protocol/xmake.lua",
    "Code/base/xmake.lua",
    "Code/client/xmake.lua",
    "Code/common/xmake.lua",
    "Code/components/xmake.lua",
    "Code/components/console/xmake.lua",
    "Code/components/es_loader/xmake.lua",
    "Code/components/imgui/xmake.lua",
    "Code/components/resources/xmake.lua",
    "Code/encoding/xmake.lua",
    "Code/higgs_bridge/xmake.lua",
    "Code/immersive_elf/xmake.lua",
    "Code/immersive_launcher/xmake.lua",
    "Code/planck_bridge/xmake.lua",
    "Code/server/xmake.lua",
    "Code/server_runner/xmake.lua",
    "Code/tests/xmake.lua",
    "Code/tp_process/xmake.lua",
    "Code/vr_gameplay_bridge/xmake.lua",
    "Code/vr_tick_bridge/xmake.lua",
    "Code/vrik_bridge/xmake.lua",
    "Libraries/xmake.lua",
    "Libraries/CommonLibSSE-NG/xmake.lua",
    "Libraries/TiltedConnect/xmake.lua",
    "Libraries/TiltedHooks/xmake.lua",
    "Libraries/TiltedReverse/xmake.lua",
    "Libraries/TiltedUI/xmake.lua",
)


class ServerDockerCacheTests(unittest.TestCase):
    def test_dependency_manifests_precede_source_and_provenance_layers(self) -> None:
        source = DOCKERFILE.read_text(encoding="utf-8")

        dependencies = "xmake require -y"
        full_source_copy = "COPY . /src"
        branch_arg = "ARG STVR_BUILD_BRANCH"
        validation = "Invalid STVR_BUILD_BRANCH provenance."
        build_info = "This file was autogenerated by the Docker build."
        build_info_template = "> Code/common/BuildInfo.h.in"
        build = "xmake -y SkyrimServerRunner"
        verify_branch = 'grep -Fqx "#define BUILD_BRANCH'
        verify_commit = 'grep -Fqx "#define BUILD_COMMIT'

        self.assertIn(dependencies, source)
        self.assertEqual(source.count(full_source_copy), 1)
        self.assertIn(branch_arg, source)
        self.assertIn(validation, source)
        self.assertIn(build_info, source)
        for manifest in DEPENDENCY_MANIFESTS:
            copy = f"COPY {manifest} /src/{manifest}"
            self.assertIn(copy, source)
            self.assertLess(source.index(copy), source.index(dependencies))

        self.assertLess(source.index(dependencies), source.index(full_source_copy))
        self.assertLess(source.index(full_source_copy), source.index(branch_arg))
        self.assertLess(source.index(branch_arg), source.index(validation))
        self.assertLess(source.index(validation), source.index(build_info))
        self.assertLess(source.index(build_info_template), source.index(build))
        self.assertLess(source.index(build), source.index(verify_branch))
        self.assertLess(source.index(build), source.index(verify_commit))

        for build_arg in ("STVR_BUILD_BRANCH", "STVR_BUILD_COMMIT"):
            self.assertNotIn(build_arg, source[: source.index(f"ARG {build_arg}")])

    def test_runtime_labels_remain_bound_to_the_same_build_identity(self) -> None:
        source = BUILD_SCRIPT.read_text(encoding="utf-8")

        self.assertIn('"STVR_BUILD_BRANCH=$branch"', source)
        self.assertIn('"STVR_BUILD_COMMIT=$network_version"', source)
        self.assertIn('"org.opencontainers.image.revision=$source_revision"', source)
        self.assertIn('"org.opencontainers.image.version=$network_version"', source)
        self.assertIn('"org.skyrimtogether.network-version=$network_version"', source)

    def test_non_buildkit_fallback_removes_each_dependency_cache_mount(self) -> None:
        source = BUILD_SCRIPT.read_text(encoding="utf-8")

        self.assertIn("replaced != 2", source)
        self.assertIn("Unable to remove Docker BuildKit cache mounts", source)


if __name__ == "__main__":
    unittest.main()
